server:
  port: 8763
eureka:
  client:
    service-url:
     defaultZone:  http://localhost:8761/eureka/
spring:
  application:
    name: eurekaClient2
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false